package com.meadowsage.guildgame.model.person;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class PersonName {
    @Getter
    private String firstName;
    @Getter
    private String familyName;

    public String getFullName() {
        return firstName + "・" + familyName;
    }

    public static PersonName generateRandom() {
        PersonName personName = new PersonName();
        Generator generator = new Generator();
        personName.firstName = generator.generate();
        personName.familyName = generator.generate();
        return personName;
    }

    public static PersonName of(String firstName, String familyName) {
        PersonName personName = new PersonName();
        personName.firstName = firstName;
        personName.familyName = familyName;
        return personName;
    }

    private static class Generator {
        private String generate() {
            String prefix = ENGLISH_PREFIX.get((int) (Math.random() * ENGLISH_PREFIX.size()));
            String suffix = ENGLISH_SUFFIX.get((int) (Math.random() * ENGLISH_SUFFIX.size()));
            String name = prefix + suffix;
            // マップの対応表で文字を結合
            for (Map.Entry<String, String> entry : NAME_FIX_MAP.entrySet()) {
                name = name.replace(entry.getKey(), entry.getValue());
            }
            return name;
        }

        private static final Map<String, String> NAME_FIX_MAP = Stream.of(new String[][]{
                        {"-", ""},
                        {"ka", "カ"},
                        {"ki", "キ"},
                        {"ku", "ク"},
                        {"ke", "ケ"},
                        {"ko", "コ"},
                        {"sa", "サ"},
                        {"shi", "シ"},
                        {"su", "ス"},
                        {"se", "セ"},
                        {"so", "ソ"},
                        {"ta", "タ"},
                        {"chi", "チ"},
                        {"tsu", "ツ"},
                        {"te", "テ"},
                        {"to", "ト"},
                        {"na", "ナ"},
                        {"ni", "ニ"},
                        {"nu", "ヌ"},
                        {"ne", "ネ"},
                        {"no", "ノ"},
                        {"ha", "ハ"},
                        {"hi", "ヒ"},
                        {"fu", "フ"},
                        {"he", "ヘ"},
                        {"ho", "ホ"},
                        {"ma", "マ"},
                        {"mi", "ミ"},
                        {"mu", "ム"},
                        {"me", "メ"},
                        {"mo", "モ"},
                        {"ya", "ヤ"},
                        {"yu", "ユ"},
                        {"yo", "ヨ"},
                        {"ra", "ラ"},
                        {"ri", "リ"},
                        {"ru", "ル"},
                        {"re", "レ"},
                        {"ro", "ロ"},
                        {"wa", "ワ"},
                        {"ga", "ガ"},
                        {"gi", "ギ"},
                        {"gu", "グ"},
                        {"ge", "ゲ"},
                        {"go", "ゴ"},
                        {"za", "ザ"},
                        {"zi", "ジ"},
                        {"zu", "ズ"},
                        {"ze", "ゼ"},
                        {"zo", "ゾ"},
                        {"da", "ダ"},
                        {"de", "デ"},
                        {"do", "ド"},
                        {"ba", "バ"},
                        {"bi", "ビ"},
                        {"bu", "ブ"},
                        {"be", "ベ"},
                        {"bo", "ボ"},
                        {"pa", "パ"},
                        {"pi", "ピ"},
                        {"pu", "プ"},
                        {"pe", "ペ"},
                        {"po", "ポ"},
                        {"kya", "キャ"},
                        {"kyu ", "キュ"},
                        {"kyo", "キョ"},
                        {"sha", "シャ"},
                        {"shu ", "シュ"},
                        {"sho", "ショ"},
                        {"cha", "チャ"},
                        {"chu ", "チュ"},
                        {"cho", "チョ"},
                        {"nya", "ニャ"},
                        {"nyu ", "ニュ"},
                        {"nyo", "ニョ"},
                        {"hya", "ヒャ"},
                        {"hyu ", "ヒュ"},
                        {"hyo", "ヒョ"},
                        {"mya", "ミャ"},
                        {"myu ", "ミュ"},
                        {"myo", "ミョ"},
                        {"rya", "リャ"},
                        {"ryu ", "リュ"},
                        {"ryo", "リョ"},
                        {"gya", "ギャ"},
                        {"gyu ", "ギュ"},
                        {"gyo", "ギョ"},
                        {"ja", "ジャ"},
                        {"ju ", "ジュ"},
                        {"jo", "ジョ"},
                        {"bya", "ビャ"},
                        {"byu ", "ビュ"},
                        {"byo", "ビョ"},
                        {"pya", "ピャ"},
                        {"pyu ", "ピュ"},
                        {"pyo", "ピョ"},
                        {"fa", "ファ"},
                        {"fi", "フィ"},
                        {"fe", "フェ"},
                        {"fo", "フォ"},
                        {"fyu", "フュ"},
                        {"wi", "ウィ"},
                        {"we", "ウェ"},
                        {"wo", "ウォ"},
                        {"va", "ヴァ"},
                        {"vi", "ヴィ"},
                        {"ve", "ヴェ"},
                        {"vo", "ヴォ"},
                        {"tsa", "ツァ"},
                        {"tsi", "ツィ"},
                        {"tse", "ツェ"},
                        {"tso", "ツォ"},
                        {"che", "チェ"},
                        {"she", "シェ"},
                        {"je", "ジェ"},
                        {"ti", "ティ"},
                        {"di", "ディ"},
                        {"du", "デュ"},
                        {"tu", "トゥ"},
                        {"a", "ア"},
                        {"i", "イ"},
                        {"u", "ウ"},
                        {"e", "エ"},
                        {"o", "オ"},
                        {"k", "ク"},
                        {"s", "ス"},
                        {"t", "ツ"},
                        {"n", "ン"},
                        {"h", ""},
                        {"m", "ム"},
                        {"y", "イ"},
                        {"r", "ル"},
                        {"w", "ウ"},
                        {"d", "ド"},
                        {"g", "グ"},
                        {"p", "プ"},
                        {"b", "ブ"},
                        {"v", "ヴ"}}
        ).collect(Collectors.toMap(data -> data[0], data -> data[1]));

        private static final List<String> ENGLISH_PREFIX = Arrays.asList(
                "ア",
                "アr",
                "アー",
                "アーd",
                "アーm",
                "アーn",
                "アk",
                "アクs",
                "アsy",
                "アs",
                "アニs",
                "アバー",
                "アポn",
                "インb",
                "w",
                "v",
                "ウェr",
                "エクs",
                "オk",
                "オクt",
                "オー",
                "カm",
                "カー",
                "カーk",
                "カr",
                "k",
                "キn",
                "g",
                "ギr",
                "クw",
                "クv",
                "グレn",
                "シュw",
                "シュv",
                "シェp",
                "スタn",
                "スt",
                "ストr",
                "ターn",
                "ダr",
                "タn",
                "ダn",
                "チェp",
                "ディn",
                "ティr",
                "ドラm",
                "トr",
                "n",
                "ナ",
                "ナn",
                "ノ",
                "ノー",
                "b",
                "p",
                "バr",
                "パーv",
                "バr",
                "ピッt",
                "フィn",
                "プーr",
                "ブラッd",
                "ブリー",
                "ブr",
                "ブレs",
                "ブレn",
                "ペn",
                "ベクs",
                "ベッk",
                "ポーs",
                "ボーn",
                "ポr",
                "ホルm",
                "ポンt",
                "m",
                "マグn",
                "モs",
                "ラn",
                "ランg",
                "リn",
                "リンg"
        );

        private static final List<String> ENGLISH_SUFFIX = Arrays.asList(
                "a",
                "aク",
                "aス",
                "aチ",
                "aム",
                "aポン",
                "aスター",
                "aルド",
                "aルト",
                "aリー",
                "aーク",
                "aーグ",
                "aース",
                "aースト",
                "aーデン",
                "aーン",
                "aージ",
                "aース",
                "iング",
                "iク",
                "iス",
                "iル",
                "iーク",
                "iーグ",
                "iースト",
                "iーン",
                "uター",
                "uレン",
                "uトーク",
                "eッド",
                "e",
                "eイ",
                "eイク",
                "eス",
                "eル",
                "eルド",
                "eート",
                "eリー",
                "oック",
                "oルト",
                "oルド",
                "oス",
                "oーグ",
                "oースト",
                "oーン",
                "oイド",
                "oット",
                "ィ",
                "ヴァ",
                "uィック",
                "uィッチ",
                "uォルド",
                "ギル",
                "uレン",
                "eート",
                "eス",
                "ショー",
                "uター",
                "スト",
                "チェス",
                "ック",
                "eィ",
                "eィン",
                "eール",
                "eン",
                "oフト",
                "oレス",
                "oルト",
                "oン",
                "eス",
                "aーグ",
                "aイズ",
                "aラ",
                "aリー",
                "aント",
                "ビー",
                "aァ",
                "uール",
                "uォス",
                "uラ",
                "eック",
                "eリー",
                "oート",
                "oープ",
                "oスト",
                "マウス",
                "マグナ",
                "iア",
                "iン",
                "uド",
                "eイ",
                "oー",
                "n"
        );
    }
}