spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
  flyway:
    clean-on-validation-error: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true

API_KEY: dummy

logging:
  level:
    root: info
    com:
      meadowsage:
        guildgame:
          mapper: debug
